### ISSUE TITLE
map cannot be called twice, why?

### ISSUE THREAD

**Issue by CodeOfCloud** [tyler1zhang/Advanture_of_Code#9]
# losing map, map cannto be used 2nd time, why?
a = range(1,10)
mymap = map(lambda x: x*x, a)
list1 = list(mymap)
list2 = list(mymap)

print(f'my list1 is {list1}')
print(f'my list2 is {list2}')

**Comment by tyler1zhang** [comment]
i found one explanation from [stackoverflow](https://stackoverflow.com/questions/36486950/python-calling-list-on-a-map-object-twice).
it mentioned the difference between iterator and generator. however, I could not fully understand it.
